# https://squidfunk.github.io/mkdocs-material/getting-started
# https://squidfunk.github.io/mkdocs-material/reference/admonitions
# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml


site_name: PiKVM Handbook
site_description: KVM over IP on Raspberry Pi
site_author: Maxim Devaev
site_url: https://pikvm.github.io/pikvm

repo_name: pikvm/pikvm
repo_url: https://github.com/pikvm/pikvm
edit_uri: ""

copyright: "Copyright &copy; 2018-2025 Maxim Devaev"

docs_dir: docs

theme:
    logo: _assets/logo.png
    favicon: _assets/favicon.ico
    name: material
    palette:
        accent: pink
    font:
        text: "arial, sans-serif"
        code: monospace
    features:
        - navigation.indexes
        - navigation.sections
        - navigation.top
        - navigation.tracking
        - navigation.expand
        - search.highlight
        - search.share
        - search.suggest

extra_css:
    - _assets/user.css

markdown_extensions:
    - admonition
    - def_list
    - attr_list
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.magiclink
    - pymdownx.tabbed:
        alternate_style: true
    - toc:
        permalink: true
    - codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs

plugins:
    - search:
        lang: en
    - mkdocs-video
    - redirects:
        redirect_maps:
            "lte.md": "modem.md"
            "gsm.md": "modem.md"
            "3g.md": "modem.md"
            "4g.md": "modem.md"
            "usb_dynamic.md": "usb.md"
            "webrtc.md": "video.md"

nav:
    - "Device guides":
        - "PiKVM V4 Mini & Plus": v4.md
        - "PiKVM V3 HAT": v3.md
        - "PiKVM Switch": switch.md
        - "DIY PiKVM V2": v2.md
        - "DIY PiKVM V1": v1.md
    - "Getting started":
        - "First steps": first_steps.md
        - "Web UI Overview": webui.md
        - "Authentication & 2FA": auth.md
        - "FAQ & Troubleshooting": faq.md
        - "Flashing OS": flashing_os.md
    - "Networking":
        - "Internet access":
            - "Port forwarding": port_forwarding.md
            - "Reverse proxy": reverse_proxy.md
            - "Tailscale VPN": tailscale.md
            - "Cloudflare Tunnel": cloudflared.md
        - "Setting up Wi-Fi": wifi.md
        - "Setting up 3G/4G/LTE modem": modem.md
        - "Let's Encrypt certificates": letsencrypt.md
    - "Video":
        - "Video modes (WebRTC, Direct)": video.md
        - "WebRTC configuration": webrtc_config.md
        - "Tuning HDMI EDID": edid.md
        - "HDMI passthrough": pass.md
    - "Peripheral devices":
        - "USB configuration": usb.md
        - "Audio / Microphone": audio.md
        - "Keyboard & mouse":
            - "Mouse modes": mouse.md
            - "Mouse jiggler": mouse_jiggler.md
            - "Pico HID (USB, PS/2)": pico_hid.md
            - "Bluetooth HID": bluetooth_hid.md
        - "Mass Storage Drive": msd.md
        - "Ethernet-over-USB": usb_ethernet.md
        - "Serial-over-USB": usb_serial.md
        - "GPIO (pins, relays, lamps, etc)": gpio.md
    - "Advanced usage":
        - "On-boot configuration": on_boot_config.md
        - "Using VNC": vnc.md
        - "Multiport KVM-over-IP": multiport.md
        - "Wake-on-LAN the server": wol.md
        - "IPMI & Redfish integration": ipmi.md
        - "Persistent storage": pst.md
        - "Prometheus monitoring": prometheus.md
        - "DIP switches": dip_switches.md
        - "USB 3.0 support": usb3v4.md
    - "Development":
        - "HTTP API reference": api.md
        - "Building PiKVM OS": building_os.md
        - "Cases for 3D printing": 3d_printing.md
    - "Legacy":
        - "Arduino HID": arduino_hid.md
        - "Big DVD images on old PiKVM": msd_legacy.md
    - "Compliance": compliance.md
