# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
# https://github.com/normanlorrain/mkdocs-thumbnails
# https://squidfunk.github.io/mkdocs-material/reference/admonitions
# https://squidfunk.github.io/mkdocs-material/reference/images
# https://blueswen.github.io/mkdocs-glightbox/caption/caption


site_name: PiKVM Handbook
site_description: KVM over IP on Raspberry Pi
site_author: Maxim Devaev
site_url: https://pikvm.github.io/pikvm

repo_name: pikvm/pikvm
repo_url: https://github.com/pikvm/pikvm
edit_uri: ""

copyright: "Copyright &copy; 2018-2025 Maxim Devaev"

docs_dir: docs

theme:
    logo: _assets/logo.png
    favicon: _assets/favicon.ico
    name: material
#    palette:
#        primary: black
#        accent: black
    font:
        text: "arial, sans-serif"
        code: monospace
    features:
        - navigation.indexes
        - navigation.sections
        - navigation.top
        - navigation.expand
#        - navigation.tabs
        - search.highlight
        - search.share
        - search.suggest
        - content.code.copy

extra_css:
    - _assets/user.css

extra_javascript:
  - _assets/add_paragraphs.js
  - _assets/scroll_to_summary.js

markdown_extensions:
    - admonition
    - def_list
    - attr_list
    - md_in_html
    - pymdownx.tilde
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.magiclink
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.blocks.caption
    - toc:
        permalink: true
        toc_depth: 3
    - codehilite:
        guess_lang: false
    - markdown_include.include:
        base_path: docs

plugins:
    - search:
        lang: en
    - mkdocs-video:
        video_autoplay: false
        video_controls: true
    - redirects:
        redirect_maps:
            "lte.md": "modem.md"
            "gsm.md": "modem.md"
            "3g.md": "modem.md"
            "4g.md": "modem.md"
            "usb_dynamic.md": "usb.md"
            "webrtc.md": "video.md"
            "first_steps.md": "cheatsheet.md"
            "cheat_sheet.md": "cheatsheet.md"
            "override.md": "config.md"
    - glightbox:
        touchNavigation: false
        loop: false
        slide_effect: slide
        width: 95%
        height: auto
        zoomable: true
        auto_caption: false
        caption_position: bottom
        background: white
        shadow: true
        manual: false
    - blog:
        blog_dir: blog
        blog_toc: true

nav:
    - "Device guides":
        - "PiKVM V4 Mini & Plus": v4.md
        - "PiKVM V3": v3.md
        - "PiKVM Switch": switch.md
        - "DIY PiKVM V2": v2.md
        - "DIY PiKVM V1": v1.md
    - "Getting started":
        - "Cheat Sheet": cheatsheet.md
        - "Web UI Overview": webui.md
        - "Configuring PiKVM": config.md
        - "Authentication & 2FA": auth.md
        - "FAQ & Troubleshooting": faq.md
        - "Flashing OS": flashing_os.md
    - "Networking":
        - "Internet access":
            - "Port forwarding": port_forwarding.md
            - "Reverse proxy": reverse_proxy.md
            - "Tailscale VPN": tailscale.md
            - "Cloudflare Tunnel": cloudflared.md
        - "Setting up Wi-Fi": wifi.md
        - "Setting up 3G/4G/LTE modem": modem.md
        - "Let's Encrypt certificates": letsencrypt.md
    - "Video":
        - "Video modes (WebRTC, Direct)": video.md
        - "WebRTC configuration": webrtc_config.md
        - "Tuning HDMI EDID": edid.md
        - "HDMI passthrough": pass.md
    - "Peripheral devices":
        - "ATX board": atx_board.md
        - "USB configuration": usb.md
        - "USB passthrough": usb_pass.md
        - "Audio / Microphone": audio.md
        - "Keyboard & mouse":
            - "Mouse modes": mouse.md
            - "Mouse jiggler": mouse_jiggler.md
            - "Pico HID (USB, PS/2)": pico_hid.md
            - "Bluetooth HID": bluetooth_hid.md
        - "Mass Storage Drive": msd.md
        - "Ethernet-over-USB": usb_ethernet.md
        - "Serial-over-USB": usb_serial.md
        - "GPIO (pins, relays, lamps, etc)": gpio.md
    - "Advanced usage":
        - "Advanced authentication": auth_advanced.md
        - "PiKVM identification": id.md
        - "On-boot configuration": on_boot_config.md
        - "Automatic snapshots": auto_snapshots.md
        - "Using VNC": vnc.md
        - "Multiport KVM-over-IP": multiport.md
        - "Wake-on-LAN the server": wol.md
        - "IPMI & Redfish integration": ipmi.md
        - "Persistent storage": pst.md
        - "Prometheus monitoring": prometheus.md
    - "Development":
        - "HTTP API reference": api.md
        - "Building PiKVM OS": building_os.md
        - "Cases for 3D printing": 3d_printing.md
    - "Legacy":
        - "Arduino HID": arduino_hid.md
        - "Big DVD images on old PiKVM": msd_legacy.md
    - "PiKVM Info":
        - "Compliance": compliance.md
        - "Blog & News":
            - blog/index.md
